version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:20.16.0-browsers
    steps:
      - checkout
      - run:
          name: Mettre à jour le cache de paquets
          command: sudo apt-get update
      - run:
          name: Installer Apache
          command: sudo apt-get install -y apache2
      - run:
          name: Installer Google Chrome
          command: |
            sudo apt-get install -y wget
            wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
            sudo apt-get update
            sudo apt-get install -y google-chrome-stable
      - run:
          name: Démarrer Apache
          command: sudo service apache2 start
      - run:
          name: Copier le fichier test.html dans le répertoire Apache
          command: sudo cp test.html /var/www/html/test.html
      - run:
          name: Lister les fichiers dans /var/www/html
          command: ls -la /var/www/html
      - run:
          name: Attendre que le serveur soit prêt
          command: |
            for i in {1..10}; do
              curl -s http://localhost/test.html && break || sleep 5
            done
      - run:
          name: Tester le serveur avec curl
          command: |
            RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost/test.html)
            if [ "$RESPONSE" -ne 200 ]; then
              echo "Erreur: le serveur a répondu avec le code HTTP $RESPONSE"
              exit 1
            fi
            echo "Le serveur a répondu avec succès avec le code HTTP $RESPONSE"
      - run:
          name: Logs du serveur
          command: sudo cat /var/log/apache2/access.log

workflows:
  test_workflow:
    jobs:
      - test
