version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:20.16.0-browsers
    steps:
      - checkout
      - run:
          name: Mettre à jour le cache de paquets
          command: sudo apt-get update
      - run:
          name: Installer un serveur HTTP (optionnel)
          command: sudo apt-get install -y apache2
      - run:
          name: Démarrer Apache pour servir les fichiers
          command: sudo service apache2 start
      - run:
          name: Installer Google Chrome
          command: |
            sudo apt-get install -y wget
            wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
            sudo apt-get update
            sudo apt-get install -y google-chrome-stable
            sudo apt-get install -y dbus
      - run:
          name: Lancer Chrome sans tête pour exécuter les tests
          command: |
            google-chrome --headless --disable-gpu --no-sandbox --remote-debugging-port=9222 --timeout=10000 http://localhost/test.html
      - run:
          name: Vérifier les logs du serveur
          command: sudo cat /var/log/apache2/access.log
workflows:
  test_workflow:
    jobs:
      - test